
#异步任务线程池的大小
task:
  corePoolSize: 8
  maxPoolSize: 16
  queueCapacity: 200
  threadNamePrefix: "WarehouseExecutor-"
# 配置aop启用
#spring:
#  aop:
#    auto: true
#    proxy-target-class: true

# 异步线程池的配置很重要
customer:
  corePoolSize: 8   #核心线程
  maximumPoolSize: 16 #最大线程
  keepAliveTime: 60000 # 单位毫秒
  queueCapacity: 200 # 队列200

#swagger线上配置成false，线下true用于生成文档
swagger:
  enable: false

spring:
  ####### 配置启用的环境  #######
  profiles:
    active: dev

#####  dev 环境配置   #####
---
spring:
  config:
    activate:
      on-profile: dev
swagger:
  enable: true
logging:
  config: classpath:log4j2-dev.xml

#####  test 环境配置   #####
---
spring:
  config:
    activate:
      on-profile: test
logging:
  config: classpath:log4j2.xml

#####  prod 环境配置   #####
---
spring:
  config:
    activate:
      on-profile: prod
logging:
  config: classpath:log4j2.xml
