spring:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo_dev?serverTimezone=UTC
    username: root
    password: 12345678
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
