#不能用localhost,否则启动报异常:Unresolved address
#tcp监听的端口
tcp:
  port: 8090
# bossGroup的线程数
parent:
  thread:
    count: 2
# worker的线程数
child:
  thread:
    count: 2
#是否使用长连接
so:
  keepalive:  true
  backlog: 100

message:
  length: 40960

